ServerName          "Production FTP Proxy"
ServerType          standalone
DefaultServer       on

Port                2121
Umask               022
MaxInstances        30

User                proftpd
Group               nogroup

LoadModule mod_proxy.c
LoadModule mod_tls.c

<IfModule mod_tls.c>
  TLSEngine on
  TLSLog /var/log/proftpd/tls.log
  TLSProtocol TLSv1.2 TLSv1.3
  TLSRSACertificateFile /etc/proftpd/ssl/proftpd.crt
  TLSRSACertificateKeyFile /etc/proftpd/ssl/proftpd.key
  TLSVerifyClient off
  TLSRequired on
</IfModule>

<IfModule mod_proxy.c>
  ProxyEngine on
  ProxyLog /var/log/proftpd/proxy.log
  ProxyRole reverse
  
  ProxyReverseServers ftp://172.40.0.40:21
  
  PassivePorts 2122 2122

  <Proxy *>
    Order allow,deny
    Allow from all
  </Proxy>
</IfModule>
