##
## Master process services
##

# IMAP service (port 143)
service imap-login {
  inet_listener imap {
    port = 143
  }
}

service imap {
  # Number of imap processes to pre-fork
  process_limit = 50
}

# Auth service (used by Postfix SASL)
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
