##
## Mailbox locations and namespaces
##

# Maildir format, stored in each user's home directory
mail_location = maildir:~/Maildir

# Let Dovecot handle mailbox creation
mail_home = /home/%u

namespace inbox {
  inbox = yes
  separator = /
}
