
services:
  pfsense-fw:
    image: ubuntu
    container_name: pfsense-fw
    privileged: true # Necesario para manipular reglas de iptables/enrutamiento
    networks:
      vpn_net:
        ipv4_address: 172.10.0.2
      services_net:
        ipv4_address: 172.20.0.2
      production_net:
        ipv4_address: 172.30.0.2
      development_net:
        ipv4_address: 172.40.0.2
    volumes:
      - ./init.sh:/init.sh
      - ./iptables.rules:/iptables.rules
      - ./dnsmasq.dhcp.conf:/etc/dnsmasq.d/dhcp.conf:ro
    command: bash /init.sh

networks:
  vpn_net:
    external: true
  services_net:
    external: true
  production_net:
    external: true
  development_net:
    external: true