# MODO SOLO DHCP PARA REDES
port=0

# Configuración para DHCP
bind-dynamic
dhcp-authoritative
log-dhcp

# Registro de concesiones DHCP 
# (Guarda información de los dispositivos que han recibido una dirección IP)
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# Configuración de DHCP para cada red
# dhcp-range: asigna un rango de direcciones IP para cada red, con su máscara de subred 
# y tiempo de concesión a una etiqueta (tag) que identifica la red
# dhcp-option: asigna opciones DHCP específicas para cada red, como la puerta de enlace (router) y el servidor DNS

# VPN network 172.10.0.0/24
dhcp-range=set:vpn,172.10.0.100,172.10.0.199,255.255.255.0,12h
dhcp-option=tag:vpn,option:router,172.10.0.2
dhcp-option=tag:vpn,option:dns-server,172.20.0.10

# Services network 172.20.0.0/24
dhcp-range=set:services,172.20.0.100,172.20.0.199,255.255.255.0,12h
dhcp-option=tag:services,option:router,172.20.0.2
dhcp-option=tag:services,option:dns-server,172.20.0.10

# Production network 172.30.0.0/24
dhcp-range=set:prod,172.30.0.100,172.30.0.199,255.255.255.0,12h
dhcp-option=tag:prod,option:router,172.30.0.2
dhcp-option=tag:prod,option:dns-server,172.20.0.10

# Development network 172.40.0.0/24
dhcp-range=set:dev,172.40.0.100,172.40.0.199,255.255.255.0,12h
dhcp-option=tag:dev,option:router,172.40.0.2
dhcp-option=tag:dev,option:dns-server,172.20.0.10
