services:
  vpn_server:
    image: linuxserver/wireguard
    container_name: vpn_server
    cap_add:
      - NET_ADMIN # Permite configurar la red dentro del contenedor
      - SYS_MODULE # Permite cargar/usar modulos del kernel
    networks:
      vpn_net:
        ipv4_address: 172.10.0.10
    sysctls:
      - net.ipv4.ip_forward=1 
      # Habilita reenvio IP para rutear trafico entre redes
      - net.ipv4.conf.all.src_valid_mark=1
      # Necesario para policy routing y marcado de paquetes en WireGuard
    env_file:
      - .env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
      - SERVERURL=${SERVERURL:-vpn.empresa.local}
      - SERVERPORT=${SERVERPORT:-51820}
      - PEERS=${PEERS:-0}
      - PEERDNS=${PEERDNS:-172.20.0.10}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.13.13.0}
      - ALLOWEDIPS=${ALLOWEDIPS:-172.10.0.0/8}
      - PERSISTENTKEEPALIVE_PEERS=${PERSISTENTKEEPALIVE_PEERS:-all}
      - LOG_CONFS=${LOG_CONFS:-true}
    volumes:
      - ./vpn-config:/config
      - /lib/modules:/lib/modules:ro # Expone modulos del kernel del host en solo lectura
    ports:
      - "51820:51820/udp" # Puerto expuesto al host para clientes externos
    restart: unless-stopped

networks:
  vpn_net:
    external: true
