[global]
    workgroup = WORKGROUP
    server string = Dev Samba Server
    security = user
    passdb backend = tdbsam
    load printers = no
    printcap name = /dev/null
    disable spoolss = yes

[desarrollo]
    path = /data/desarrollo
    valid users = empleado1, empleado2, empleado3, empleado4, empleado5
    read only = no
    browseable = yes
    create mask = 0600
    directory mask = 0700

[revision]
    path = /data/revision
    valid users = empleado1, empleado2, empleado3, empleado4, empleado5, revisor
    read only = no
    browseable = yes
    create mask = 0660
    directory mask = 0770

[publico]
    path = /data/publico
    valid users = empleado1, empleado2, empleado3, empleado4, empleado5, revisor, ftp
    read only = yes
    write list = revisor
    browseable = yes
    create mask = 0644
    directory mask = 0755
    force user = revisor
