[Interface]
Address = ${INTERFACE}.254
ListenPort = 51820
PrivateKey = $(cat /config/server/privatekey-server)
PostUp = iptables -t nat -A POSTROUTING -s 172.10.0.0/24 -o eth0 -j MASQUERADE
# Hace NAT de salida para que clientes VPN salgan por la IP del contenedor
PostUp = iptables -A FORWARD -s 172.10.0.0/24 -j ACCEPT 
# Permite reenviar trafico cuyo origen es la red VPN hacia otras redes
PostUp = iptables -A FORWARD -d 172.10.0.0/24 -j ACCEPT 
# Permite trafico de retorno o entrada hacia clientes de la red VPN
