[Interface]
Address = ${INTERFACE}.254
ListenPort = 51820
PrivateKey = $(cat /config/server/privatekey-server)
PostUp = iptables -t nat -A POSTROUTING -s 172.10.0.0/24 -o eth0 -j MASQUERADE
PostUp = iptables -A FORWARD -s 172.10.0.0/24 -j ACCEPT
PostUp = iptables -A FORWARD -d 172.10.0.0/24 -j ACCEPT
